### ISSUE TITLE
kubie and `gcloud container clusters get-credentials`

### ISSUE THREAD

**Issue by socketbox** [sbstp/kubie#106]
If I'm already in a kubie context, kubie has set `$KUBECONFIG` to a temporary file in `/tmp/kubie-config<random>`

When I go to add a GKE cluster using `gcloud`, that tool adds the new credentials to this temporary file (see https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials): 
>It takes a project and a zone as parameters, passed through by set defaults or flags. By default, credentials are written to HOME/.kube/config. You can provide an alternate path by setting the KUBECONFIG environment variable. If KUBECONFIG contains multiple paths, the first one is used.

There are two subsequent problems:
1. `kubie` itself doesn't acknowledge the presence of the new cluster in its own temporary file, so I can't switch to the new cluster using `kubie ctx`
2. The cluster credentials are essentially ephemeral and useless, as they've not been added to the canonical kubeconfig that everything else on the system refers to

Not really sure how to work around this, other than remembering to exit out of the kubie context before adding a cluster.

**Comment by TyBrown** [comment]
We use a similar tool to generate credentials for users as well... since we built our tool internally, we added some detection into it to ensure that the environment variable `KUBIE_ACTIVE` is not set, if it is set, then we error out.

For gcloud, you might be able to write a small bash wrapper script of some sort to do this check for you... something along the lines of:
```
#!/bin/bash

if [[ -v KUBIE_ACTIVE ]]; then
    echo "Kubie is active in this shell, trying to login with Kubie active is a bad idea" >&2
    exit 1
fi

exec gcloud $@
```

It's not exactly pretty... but I hope this helps. :)

**Comment by socketbox** [comment]
Thanks for this! I think it will prevent a fresh round of confusion.
